// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBab6h-PFGu73uNqaqGZrgbsEbQ4DMvytU',
    appId: '1:1095022035275:web:bdc143feda6fe948f828ce',
    messagingSenderId: '1095022035275',
    projectId: 'okekem-flutter-app',
    authDomain: 'okekem-flutter-app.firebaseapp.com',
    storageBucket: 'okekem-flutter-app.firebasestorage.app',
    measurementId: 'G-DXQ5FJGG5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvAyFcYj4mTLtL9JNwEynBRSFPZ4mRfMI',
    appId: '1:1095022035275:android:0bbee047c9eb1294f828ce',
    messagingSenderId: '1095022035275',
    projectId: 'okekem-flutter-app',
    storageBucket: 'okekem-flutter-app.firebasestorage.app',
  );

}